name: Tests

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  unit_tests:
    name: ${{ matrix.python_version }} unit tests ${{ matrix.optional_libraries }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python_version: [ "3.6", "3.7", "3.8" ]
        optional_libraries: [ "minimal", "optional" ]
    steps:
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Build featuretools package
        run: make package_featuretools
      - name: Set up pip and graphviz
        run: |
          pip config --site set global.progress_bar off
          python -m pip install --upgrade pip
          sudo apt update && sudo apt install -y graphviz
      - if: ${{ matrix.optional_libraries != 'optional' }}
        name: Install featuretools with test requirements (no optional requirements)
        run: |
          python -m pip install -e unpacked_sdist/
          python -m pip install -r unpacked_sdist/test-requirements.txt
      - if: ${{ matrix.optional_libraries == 'optional' }}
        name: Install featuretools with test requirements and optional requirements
        run: |
          sudo apt install -y openjdk-11-jre-headless
          JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"
          python -m pip install -e unpacked_sdist/[koalas]
          python -m pip install -r unpacked_sdist/test-requirements.txt
      - if: ${{ matrix.python_version != 3.6 || matrix.optional_libraries != 'optional' }}
        name: Run unit tests (no code coverage)
        run: |
          cd unpacked_sdist
          pytest featuretools/ -n 2
      - if: ${{ matrix.python_version == 3.6 && matrix.optional_libraries == 'optional' }}
        name: Run unit tests with code coverage
        run: |
          python -m pip install "$(cat dev-requirements.txt | grep codecov)"
          coverage erase
          cd unpacked_sdist/
          coverage erase
          pytest featuretools/ -n 2 --cov=featuretools --cov-config=../.coveragerc
      - if: ${{ matrix.python_version == 3.6 && matrix.optional_libraries == 'optional' }}
        name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
