name: Release Notes Updated

on:
  pull_request:
    types: [ opened, synchronize ]
  push:
    branches-ignore:
      - main

jobs:
  release_notes_updated:
    name: Release Notes Updated
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Debug PR type
        run: |
          if [[ $(expr match "${{ github.event.pull_request.head.ref }}" "release_v[0-9.]\+") -gt 0 ]]; then
            echo This is a release PR;
          elif [[ $(expr match "${{ github.event.pull_request.head.ref }}" "dep-update-[a-zA-Z0-9]*") -gt 0 ]]; then
            echo This is a dependency update PR;
          elif [[ $(expr match "${{ github.event.pull_request.head.ref }}" "[0-9.]{4}.*") -gt 0 ]]; then
            echo This is an even more regular file
          else
            echo This is a regular PR;
          fi
            echo ${{ github.event.pull_request.head.ref }}
      - run: |
          echo "${{ github.base_ref }}"
          echo "${{ github.event_name }}"
          echo "${{ github.event.number }}"
          echo "${{ github.event.issue.number }}"
          echo "${{ github.event.issue.pull_request }}"
          echo "${{ github.event.pull_request.head.ref }}"
      - name: Release notes added
        run: |
          if [[ $(expr match "${{ env.BRANCH_REF }}" "release_v[0-9.]\+") -gt 0 ]]; then
            exit 0;
          elif [[ $(expr match "${{ env.BRANCH_REF }}" "dep-update-[a-zA-Z0-9]*") -gt 0 ]]; then
            exit 0;
          fi
          cat docs/source/release_notes.rst | grep ":pr:\`${{ github.event.number }}\`"